### ISSUE TITLE
depois que adicionei o mod apareceu esse problema

### ISSUE THREAD

**Issue by XXLUCASFBXX** [Domaman202/AE2AOFE#8]
[STELARIS] ---------- Detected server process in a crashed state! ----------
[STELARIS] Exit code: 1
[STELARIS] Out of Memory: false
[STELARIS] Error Response: 
[STELARIS] Server process detected as entering a crashed state; rebooting.
[STELARIS] Server marked as STARTING
[STELARIS] Checking size of server data directory...
[STELARIS] Disk Usage: 870M / 61440M
[STELARIS] Ensuring file permissions.
[STELARIS] Running server preflight.
[STELARIS] Starting server container.
Detected java version as 'Java 8' automatically.
This choice can be reset by deleting the 'disable_prompt_for_java_version' file.
:/home/container$ java8 -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar forge-1.16.5-36.2.34.jar
[06:16:37] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.34, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[06:16:37] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_312 by Private Build
[06:16:37] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[06:16:37] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/container/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[06:16:39] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[06:16:39] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[06:16:39] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[06:16:39] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [de.maxhenkel.miningdimension.mixin.MixinConnector]
[06:16:40] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[06:16:40] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[06:16:40] [main/WARN] [mixin/]: Reference map 'modid.refmap.json' for rsinfinitybooster.mixins.json could not be read. If this is a development environment you can ignore this message
[06:16:40] [main/WARN] [mixin/]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[06:16:40] [main/WARN] [mixin/]: Reference map 'createdeco.refmap.json' for createdeco.mixins.json could not be read. If this is a development environment you can ignore this message
[06:16:40] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/gravestone/events/DeathEvents (java.lang.ClassNotFoundException: null)
[06:16:40] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/corpse/events/DeathEvents (java.lang.ClassNotFoundException: null)
[06:16:40] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[06:16:40] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[06:16:40] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Patching LivingEntity#blockUsingShield
[06:16:40] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Patching LivingEntity#applyPotionDamageCalculations
[HammerLib] Transforming ServerPlayNetHandler!
[HammerLib] Tapping into sendPacket (func_211148_a)
[06:16:40] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screen/CreateWorldScreen for invalid dist DEDICATED_SERVER
[06:16:40] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/screen/CreateWorldScreen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/CreateWorldScreen for invalid dist DEDICATED_SERVER)
[06:16:40] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.screen.CreateWorldScreen was not found mixins.defaultoptions.json:CreateWorldScreenAccessor
[06:16:40] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/GameSettings for invalid dist DEDICATED_SERVER
[06:16:40] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/GameSettings (java.lang.RuntimeException: Attempted to load class net/minecraft/client/GameSettings for invalid dist DEDICATED_SERVER)
[06:16:40] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.GameSettings was not found mixins.defaultoptions.json:GameSettingsMixin
[HammerLib]: Patching DataPackRegistries#<init>
[06:16:41] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching DataPackRegistries#<init>
[06:16:41] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[06:16:41] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[06:16:41] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LootTableManager#apply
[06:16:42] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[06:16:42] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Patching LivingEntity#blockUsingShield
[06:16:42] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Patching LivingEntity#applyPotionDamageCalculations
[06:16:42] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[06:16:42] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[06:16:42] [main/FATAL] [mixin/]: Mixin apply failed ae2ao.mixins.json:ItemEntityMixin -> net.minecraft.entity.item.ItemEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method getItem in ae2ao.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.entity.item.ItemEntity. Using refmap ae2ao.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getItem in ae2ao.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.entity.item.ItemEntity. Using refmap ae2ao.refmap.json
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:442) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:415) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312] {}
at net.minecraft.block.Blocks.<clinit>(Blocks.java:30) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:object_holder_definalize:A,re:mixin,pl:accesstransformer:B,pl:object_holder_definalize:A}
at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12) ~[?:?] {re:classloading}
at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11) ~[?:?] {re:classloading}
at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33) ~[?:?] {re:classloading}
at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89) ~[?:?] {re:classloading}
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_312] {}
at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) ~[?:?] {re:classloading}
at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) ~[?:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:92) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] {}
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] {}
at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.34.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.34.jar:?] {}
at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.34.jar:?] {}
Exception in thread "main" [06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at java.lang.reflect.Method.invoke(Method.java:498)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       ... 7 more
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.server.Main.main(Main.java:92)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    ... 13 more
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ae2ao.mixins.json:ItemEntityMixin] from phase [DEFAULT] in config [ae2ao.mixins.json] FAILED during APPLY
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    ... 33 more
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getItem in ae2ao.mixins.json:ItemEntityMixin was not located in the target class net.minecraft.entity.item.ItemEntity. Using refmap ae2ao.refmap.json
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:442)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:415)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[06:16:42] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    ... 33 more
[STELARIS] Server marked as OFF

[STELARIS] ---------- Detected server process in a crashed state! ----------
[STELARIS] Exit code: 1
[STELARIS] Out of Memory: false
[STELARIS] Error Response: 
[STELARIS] Aborting automatic reboot due to crash within the last 60 seconds.

**Comment by PashkovD** [comment]
Thanks for the feedback. Getting to work

**Comment by PashkovD** [comment]
Corected version 8.1.1 uploded to the curse forge. After "Under Review" you can download file.
